---
- name: Backup data file for startup
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Copy files
      command: bash PATH_TO_ELECT/scripts/run/copyDB.sh {{ sourceFileDir }} {{ targetFileDir }} {{ configureFileDir }}
      vars:
        sourceFileDir: "PATH_TO_ELECT/src/elect/data"
        targetFileDir: "PATH_TO_DB_BACKUP/Scheme/DATAPATH"
        configureFileDir: "PATH_TO_ELECT/src/elect/conf/elect.yaml"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"
    - name: Wait until copy is done
      pause:
        seconds: 5
